version: '3'
services:
  jekyll:
    build:
        context: .
        dockerfile: .Dockerfile
    image: jekyll-build
    container_name: jekyll
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    command: "bundle exec jekyll serve --host 0.0.0.0 --trace --incremental"
